### ISSUE TITLE
How to inspect scss file for css modifcations during chrome debuging

### ISSUE THREAD

**Issue by V2NileshSukalikar** [sketch7/angular-skeleton-app#3]
All scss files are genrating on index.html page inside link style tag. Its hard to detect which css class is coming from which scss file. Pleas explain the way to solve this problem.

**Comment by stephenlautier** [comment]
They are added like that in order for HMR to work correctly, so you can do changes save and you see them immediately. They get bundled when you run it in prod mode e.g. `npm run start:prod` in external css file.

To be clear in this template uses the angular-cli default structure/build process, so if you have further questions I suggest you look into that as you'll find more help. Unfortunately yes it seems to be a bit of a pain to debug with browser debugging, not sure if its possible to enable sourcemaps for dev. 

Just a tip - since it uses emulated "shadow dom" everything is scoped, only the `src/styles.scss` is not, so according to the element you are inspecting see the relative component. Hope it helps.

**Comment by V2NileshSukalikar** [comment]
Thanks for the update, Yes looking for the respective component css is the solution but this will duplicate lots of style classes. It would be great if we get to know which css file is actually affecting the classes directly from the browser while we are developing.
